### ISSUE TITLE
Init Naming Conflicts

### ISSUE THREAD

**Issue by JacksonUtsch** [stackotter/swift-bundler#1]
Using the init command uses the directory naming for its content. I initialized under a directory "bundler-testing" which created a compile error with the character `-`. This exception can be handled with a character substitute such as `_` or the init command could include a name and create the associated directory which seems more consistent with existing cli's.

**Comment by stackotter** [comment]
Thanks for reporting that, I think the swift pm cli takes the substitution approach, I'm mostly trying to stay consistent-ish with the swiftpm cli. I'll add that substitution to my code. For now you can specify a package name to init with `--name`

**Comment by stackotter** [comment]
Actually, I might do it the second way. It makes more sense, I don't really know why swiftpm doesn't do it that way

**Comment by stackotter** [comment]
The init command is now `swift bundler init [name]` and it creates a directory with the same name as the package and initialises the package in there.
