### ISSUE TITLE
iOS build support

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-bundler#2]
This shouldn't be too difficult. Just need to target the build for iOS and then create an ipa instead of a .app (the structure seems pretty similar in some ways.

**Comment by ninjadev64** [comment]
stackotter/delta-client#13

**Comment by stackotter** [comment]
This is in the process of being implemented in the sponsor-only version of Swift Bundler (see https://swiftbundler.dev).

**Comment by stackotter** [comment]
And it's mostly working, so I'll close this issue.
