### ISSUE TITLE
[Quickie] Possible to tag a new release from the main branch?

### ISSUE THREAD

**Issue by furby-tm** [stackotter/swift-bundler#34]
Hey there!

I'd like to set a package dependency on `swift-bundler` from my [**MetaverseKit Package**](https://github.com/wabiverse/MetaverseKit), so that consumers of my package can transitively use `swift-bundler` as a swift build tool plugin using `swift package plugin bundler`. Specifically, I'm looking to use it to bundle **visionOS** apps, but there is no tagged version incorporating those changes as of yet, and since I expect this package to grow in popularity given it's the central core dependency for powering the initial working support of [**Pixar's USD for Swift**](https://github.com/wabiverse/SwiftUSD) package, I'd like to ensure I'm pulling from the official source, which is you @stackotter!

**SwiftPM** is quite strict about versioning, so if I were to tag a dependency on the bundler at the `main` branch, then it would wreak havoc for consumers depending on my package which I'd certainly like to avoid.

Thanks!

**Comment by furby-tm** [comment]
Actually, it appears **v2.0.4** has never been usable by SwiftPM due to the **swift-argument-parser** dependency being set to the **main** branch at the time.

However, for this package to resolve without SwiftPM rejecting it, it looks like all that is needed is to:

- change from `branch: "main"` to `from: "0.5.5"` for the **TOMLKit** package in the current configuration below:

https://github.com/stackotter/swift-bundler/blob/78755596fda0a9b9f7314c0e1461d7a31b7b4252/Package.swift#L15

```swift
Computing version for https://github.com/stackotter/swift-bundler.git

error: Dependencies could not be resolved because package 'swift-bundler' is required using a stable-version but 'swift-bundler' depends on an unstable-version package 'swift-argument-parser' and root depends on 'swift-bundler' 2.0.4..<3.0.0.
'swift-bundler' {2.0.4..<2.0.5, 2.0.6..<3.0.0} cannot be used because package 'swift-bundler' is required using a stable-version but 'swift-bundler' depends on an unstable-version package 'swift-argument-parser'.
'swift-bundler' {2.0.4, 2.0.6..<3.0.0} cannot be used because no versions of 'swift-bundler' match the requirement 2.0.6..<3.0.0 and package 'swift-bundler' is required using a stable-version but 'swift-bundler' depends on an unstable-version package 'swift-argument-parser'.
```

**Comment by stackotter** [comment]
First up, thank you for using Swift Bundler!

Unfortunately (for tagging) I’m currently working towards a release which I’d like to have automatic code signing (like Xcode) and maybe a way to generate archives for uploading to the App Store, so I’d prefer not to tag it right now. Would it work for now if you instead depended on a specific commit?

**Comment by furby-tm** [comment]
Ah! I did not know that was possible with SwiftPM, do you know if that has any adverse effects to consumers depending on the package?

**Comment by stackotter** [comment]
I don't think it has any effects? But I would have to check (won't be able to check until Monday cause I'm away from my laptop though)

**Comment by furby-tm** [comment]
No need to worry; I plan to address this before the end of the day and will inform you if any issues arise with pinning a specific commit hash.

While directly incorporating package dependencies into your own package with SwiftPM is generally straightforward, it can become somewhat challenging when dealing with products from packages intended for consumption by other packages.

The [observed behavior](https://forums.swift.org/t/swiftpm-must-relax-its-versioning-requirements-for-dependencies/63969) in this case illustrates the somewhat stringent versioning requirements imposed by SwiftPM.

**Comment by stackotter** [comment]
> The [observed behavior](https://forums.swift.org/t/swiftpm-must-relax-its-versioning-requirements-for-dependencies/63969) in this case illustrates the somewhat stringent versioning requirements imposed by SwiftPM.

Yeah SwiftPM can be pretty annoying about versioning.

> I'm contemplating creating a separate Swift package for it and
> wanted to inquire whether you think it could be beneficial for
> use with your [Swift Cross UI](https://github.com/stackotter/swift-cross-ui) project.

It could be interesting to try implementing an experimental ImGui backend for SwiftCrossUI at some point, but I'm not planning on doing that anytime soon so don't worry about making it a separate package if it's a hassle. ImGui follows a very different paradigm to the frameworks which I've built backends for so far, and it'd be pretty difficult to retrofit it in.

**Comment by furby-tm** [comment]
Update, finally got around to whipping up a simple command line plugin for the bundler:
https://github.com/stackotter/swift-bundler/pull/36

**Comment by furby-tm** [comment]
The ability to follow the strict versioning requirements of SwiftPM have been resolved with https://github.com/stackotter/swift-bundler/pull/36
