### ISSUE TITLE
Error when running MetalSwiftUI Template: NSViewRepresentables must be value types: MetalView<TriangleRenderer>

### ISSUE THREAD

**Issue by benjiwolff** [stackotter/swift-bundler#39]
Creating a new app using `swift bundler create MetalTest --template MetalSwiftUI` and running the app without modification (`swift bundler run`) yields the following terminal output.

```
info: Bundling 'MetalTest.app'
info: Creating 'MetalTest.app'
info: Copying executable
info: Creating 'PkgInfo'
info: Creating 'Info.plist'
info: Fixing and copying resource bundle 'MetalTest_MetalTest.bundle'
info: Compiling metal shaders
info: Copying dynamic libraries
info: Done in 6.30s. App bundle located at './.build/bundler/MetalTest.app'
info: Running 'MetalTest.app'
SwiftUI/NSViewRepresentable.swift:246: Fatal error: NSViewRepresentables must be value types: MetalView<TriangleRenderer>
error: Failed to run app executable: The process returned a non-zero exit status (5)
```

Platform: M2 Max MacBook, macOS Sonoma 14.2.1
swift-bundler version: v2.0.3

**Comment by stackotter** [comment]
Thanks for reporting this. I've pushed a fix to `swift-bundler-templates` now, it seems to be working on my end. Hopefully running `swift bundler templates update` and creating a new project from the template should fix your issue.

Feel free to reopen the issue if you still face any problems with the template!

**Comment by benjiwolff** [comment]
Apparently, your change has not arrived in `swift-bundler-templates`. Push harder!

**Comment by stackotter** [comment]
I’m pretty sure it did: https://github.com/stackotter/swift-bundler-templates/tree/v3. It’s only on the v3 branch (main is v1, due to not planning ahead when I was designing the templating system lol. If you have the latest commit of swift bundler, it should be using the v3 templates.

**Comment by benjiwolff** [comment]
Ah, I see.  That explains why it _should_ work now. However, I just ran
```
swift bundler templates update
swift bundler create MetalSwiftUI --templates MetalSwiftUI
cd MetalSwiftUI
swift run
```
and got the same error still. 🤔

**Comment by benjiwolff** [comment]
Could it be possble, that the class is still used since the MetalSwiftUI package is constrained to only macOS 11 and up instead of 13 and up?

**Comment by stackotter** [comment]
> Could it be possble, that the class is still used since the MetalSwiftUI package is constrained to only macOS 11 and up instead of 13 and up?

Nah, the availability checks are performed at runtime so that shouldn’t be an issue.

> Ah, I see. That explains why it _should_ work now. However, I just ran
> 
> ```
> swift bundler templates update
> swift bundler create MetalSwiftUI --templates MetalSwiftUI
> cd MetalSwiftUI
> swift bundler run
> ```
> 
> and got the same error still. 🤔

If you go to `~/Library/Application Support/dev.stackotter.swift-bundler/templates` you should find yourself in a clone of swift-bundler-templates. What’s the branch and latest commit?

In your commands you used `--templates` which should be `--template`, but the command worked so I’m assuming that’s just a GitHub issues typo.

**Comment by benjiwolff** [comment]
The branch is `main` and the commit is `ff8c6dacbdb0f6717a9c2bc3f2c285c3a12d63ec`. 😅

**Comment by stackotter** [comment]
Ah, try switching that to the `v3` branch, I’ll have to look into that issue.

**Comment by benjiwolff** [comment]
Got this to finally work after switching to the main branch of swift-bundler and running `swift bundler templates update`.
