### ISSUE TITLE
Templates come without Bundler.toml

### ISSUE THREAD

**Issue by benjiwolff** [stackotter/swift-bundler#40]
Running the following command
```
swift bundler create Test --template MetalSwiftUI
```
results in a folder that does not contain a Bundler.toml (regardless of template choice).

As a result, doing
```
cd Test 
swift bundler run
```
yields the following error
```
error: Failed to read the configuration file at './Bundler.toml'. Are you sure that it exists?
```

MacOS 14.3 (23D56)
swift-bundler v2.0.5 (according to mint, even though the latest github release is v2.0.4)
templates: up-to-date and on branch `v3 (843e25997646e75b4365cb3d0f8e5dc6f7ca94bd)`, **works perfectly on the main branch**

**Comment by stackotter** [comment]
You need to install Swift Bundler from the `main` branch (with `mint install stackotter/swift-bundler@main`), the new updated templates only affect `v3` (the templates version must match the swift bundler version).

**Comment by stackotter** [comment]
The `v3` templates are compatible with the latest `main` branch commit, just not with the latest release (which is still `v2`). Sorry, I phrased my previous comment poorly.

**Comment by benjiwolff** [comment]
I can confirm, the issue is resolved after switching to the main branch of swift-bundler.
