### ISSUE TITLE
`swift bundler templates list` fails to read manifest for vscode templates

### ISSUE THREAD

**Issue by benjiwolff** [stackotter/swift-bundler#41]
Running
```
swift bundler templates list
```
yields the following error
```
error: Failed to read the contents of the manifest for the 'VSCode' template
```

MacOS 14.3 (23D56)
swift-bundler v2.0.5 (according to mint, even though the latest github release is v2.0.4)
templates: up-to-date and on branch v3 (843e25997646e75b4365cb3d0f8e5dc6f7ca94bd), **runs successfully on the main branch**

**Comment by stackotter** [comment]
As per #40, let me know if this is fixed once you update your Swift Bundler version to the latest commit (v3 is the current development version, but not a tagged release yet cause it's not ready).

**Comment by benjiwolff** [comment]
Yes, upgrading to the main branch version fixed the issue.

**Comment by stackotter** [comment]
Awesome, thanks 👍
