### ISSUE TITLE
Tries to launch the app despite build errors

### ISSUE THREAD

**Issue by benjiwolff** [stackotter/swift-bundler#42]
Trying to run
```
swift bundler run
```
when there are build errors, causes the app to launch and crash.

```
Building for debugging...
[0/4] Copying ShaderTypes.metal
[0/4] Copying Vertex.metal
[1/4] Copying Fragment.metal
[4/13] Compiling MetalSwiftUI RenderCoordinator.swift
[5/13] Compiling MetalSwiftUI TriangleRenderer.swift
[6/13] Compiling MetalSwiftUI Renderer.swift
[7/13] Emitting module MetalSwiftUI
[8/13] Compiling MetalSwiftUI MetalSwiftUIApp.swift
[9/13] Compiling MetalSwiftUI TriangleView.swift
[10/13] Compiling MetalSwiftUI MetalView.swift
[11/13] Compiling MetalSwiftUI MetalUtil.swift
[12/13] Compiling MetalSwiftUI resource_bundle_accessor.swift
[12/13] Linking MetalSwiftUI
Build complete! (4.34s)
SwiftUI/NSViewRepresentable.swift:246: Fatal error: NSViewRepresentables must be value types: MetalView<TriangleRenderer>
error: Failed to run app executable: The process returned a non-zero exit status (5)
info: Starting debug build
info: Bundling 'MetalSwiftUI.app'
info: Creating 'MetalSwiftUI.app'
info: Copying executable
info: Creating 'PkgInfo'
info: Creating 'Info.plist'
info: Fixing and copying resource bundle 'MetalSwiftUI_MetalSwiftUI.bundle'
info: Compiling metal shaders
info: Copying dynamic libraries
info: Done in 5.20s. App bundle located at './.build/bundler/MetalSwiftUI.app'
info: Running 'MetalSwiftUI.app'
```

<img width="271" alt="image" src="https://github.com/stackotter/swift-bundler/assets/103897890/26a4c129-51ee-4776-ae53-ab32db957107">

Could it be that apple changed the exit code if the build fails with `swift build`?

swift-driver version: 1.87.3
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
MacOS 14.3 (23D56)
swift-bundler v2.0.5 (according to mint, even though the latest github release is v2.0.4)

**Comment by stackotter** [comment]
That's a fatal runtime error which only happens after the app gets run, the logs contain 'Build complete!' from SwiftPM and no compile time errors (it just looks like a build error in the logs you included cause for some reason your stderr and stdout have been separated out and concatenated; all of stderr followed by all of stdout)
